// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/15/2026, 1:18:38 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/a1234/Documents/project/pilot-mobile-application/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1234/Documents/project/pilot-mobile-application/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1234/Documents/project/pilot-mobile-application/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1234/Documents/project/pilot-mobile-application/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1234/Documents/project/pilot-mobile-application/plugins/**/*.{js,ts,mjs}","/Users/a1234/Documents/project/pilot-mobile-application/composables/**/*.{js,ts,mjs}","/Users/a1234/Documents/project/pilot-mobile-application/utils/**/*.{js,ts,mjs}","/Users/a1234/Documents/project/pilot-mobile-application/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a1234/Documents/project/pilot-mobile-application/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/a1234/Documents/project/pilot-mobile-application/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/a1234/Documents/project/pilot-mobile-application/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;